[package]
name = "peace"
version = "0.2.1"
authors = ["PurePeace <940857703@qq.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/pure-peace/peace"
default-run = "peace"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.5.4"
actix-multipart = "0.3"
actix-rt = "1.1.1"
actix-web = "3.1.0"
actix-web-prom = "0.5.1"
askama = "0.10.5"
async-std = "1.9.0"
chrono = "0.4.19"
colored = "2.0.0"
config = "0.10.1"
deadpool-postgres = "0.5.6"
deadpool-redis = "0.6.1"
derivative = "2.2.0"
dotenv = "0.15.0"
enum-primitive-derive = "0.2.1"
env_logger = "0.8.3"
field_names = "0.1.1"
futures = "0.3.12"
hashbrown = "0.9.1"
json = "0.12.4"
lazy_static = "1.4.0"
log = "0.4.14"
maxminddb = { version = "0.17.2", features = ["mmap"] }
md5 = "0.7.0"
memmap = "0.7.0"
num-traits = "0.2.14"
paste = "1.0.5"
postgres-types = { version = "0.1.2", features = ["derive", "with-chrono-0_4", "with-serde_json-1"] }
prometheus = { version = "0.11.0", features = ["process"] }
queue = "0.3.1"
rand = "0.8.3"
regex = "1.4.3"
reqwest = { version = "0.10.10", features = ["rustls-tls", "json"], default-features = false }
rust-argon2 = "0.8.3"
serde = { version = "1.0.123", features = ["derive"] }
serde_derive = "1.0.123"
serde_json = "1.0.62"
serde_postgres = "0.2.0"
serde_qs = "0.8.2"
serde_str = "0.1.0"
strum = "0.20"
strum_macros = "0.20"
tokio-pg-mapper = "0.1.8"
tokio-pg-mapper-derive = "0.1.5"
tokio-postgres = { version = "0.5.5", features = ["with-chrono-0_4", "with-serde_json-1"] }
uuid = { version = "0.8.1", features = ["v4"] }


[dev-dependencies]
criterion = "0.3.4"

[[bench]]
name = "packet_write"
harness = false


# link-time-optimization
# Enabling makes the compiled program size smaller and higher performance, 
# but it will extend compilation time.
[profile.release]
lto = true
codegen-units = 1
opt-level = 's'

# link-time-optimization
# Enabling makes the compiled program size smaller and higher performance, 
# but it will extend compilation time.
[profile.bench]
lto = false
