[package]
name = "peace"
version = "0.0.1"
authors = ["PurePeace <940857703@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.5.2"
actix-multipart = "0.3"
actix-web = "3.2.0"
actix-web-prom = "0.5.0"
async-std = "1.7.0"
bytes = "0.6.0"
colored = "2.0.0"
config = "0.10.1"
deadpool-postgres = "0.5.6"
deadpool-redis = "0.6.1"
dotenv = "0.15.0"
env_logger = "0.8.1"
futures = "0.3.8"
hashbrown = "0.9.1"
lazy_static = "1.4.0"
log = "0.4.11"
prometheus = { version = "0.10.0", features = ["process"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_derive = "1.0.117"
serde_qs = "0.7.0"
tokio-postgres = "0.5.5"
uuid = { version = "0.8.1", features = ["v4"] }

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "packet_write"
harness = false

# link-time-optimization
# Enabling makes the compiled program size smaller and higher performance, 
# but it will extend compilation time.
[profile.release]
lto = false

# link-time-optimization
# Enabling makes the compiled program size smaller and higher performance, 
# but it will extend compilation time.
[profile.bench]
lto = false
