[package]
name = "peace"
version = "0.0.1"
authors = ["PurePeace <940857703@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.1.0"
tokio-postgres = "0.5.1"
deadpool-postgres = "0.5.6"
deadpool-redis = "0.6.1"
config = "0.10.1"
dotenv = "0.15.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_derive = "^1.0.8"
log = "0.4.11"
env_logger = "0.8.1"
colored = "2.0.0"
