# Basic
hard_tabs = false
max_width = 80
use_small_heuristics = "Max"
# Imports
reorder_imports = true
# Consistency
newline_style = "Unix"
# Misc
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
use_field_init_shorthand = true
edition = "2021"
