[package]
name = "domain_chat"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[features]


[dependencies]
serde = { workspace = true, features = ["derive"] }
bitmask-enum = { workspace = true }
enum-primitive-derive = { workspace = true }
num-traits = { workspace = true }
