[package]
name = "peace_services"
version = "0.1.0"
edition = "2021"
authors = ["Pure-Peace"]
repository = "https://github.com/pure-peace/peace"
homepage = "https://github.com/pure-peace/peace"


[dependencies]
tokio = { version = "1" }
tonic = "0.8"
futures = "0.3"
chrono = "0.4"
uuid = { version = "1.3", features = ["v4"] }

bancho-packets = { path = "../../lib/bancho-packets" }
tools = { path = "../../lib/tools", features = ["async_collections"] }

peace_logs = { path = "../../frame/logs" }
peace_db = { path = "../../core/db" }
peace_pb = { path = "../../core/pb" }
peace_domain = { path = "../../core/domain" }
peace_repositories = { path = "../../core/repositories" }


[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
