[package]
name = "geoip-server"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[[bin]]
name = "geoip-server"
path = "src/main.rs"


[dependencies]
tonic = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive"] }
clap-serde-derive = { workspace = true }


peace_logs = { path = "../../frame/logs", features = ["grpc", "cli"] }
peace_rpc = { path = "../../frame/rpc", features = [
    "tls",
    "admin_endpoints",
    "reflection",
] }


peace_pb = { path = "../../core/pb" }
peace_services = { path = "../../core/services" }
peace_domain = { path = "../../core/domain" }
