[package]
name = "peace_gateway"
description = "Peace Gateway Service"
version = "0.1.0"
edition = "2021"
authors = ["Pure-Peace"]
repository = "https://github.com/pure-peace/peace"
homepage = "https://github.com/pure-peace/peace"

[features]
default = ["tls"]
tls = ["peace_api/tls"]

[[bin]]
name = "gateway-server"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# core
axum = { version = "0.6.0" }
tokio = { version = "1.0" }
tower = { version = "0.4" }
tonic = { version = "0.8", features = ["tls"] }
anyhow = { version = "1.0" }

# openapi
utoipa = { version = "2.4.2" }

# serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# utils
clap = { version = "4.0", features = ["derive"] }
clap-serde-derive = "0.2.0"
once_cell = "1.16"

# local crates
peace_logs = { path = "../../frame/logs", features = ["openapi_axum", "cli"] }
peace_api = { path = "../../frame/api", features = ["tls"] }
peace_pb = { path = "../../frame/pb", features = ["bancho"] }
tools = { path = "../../lib/tools" }


[dev-dependencies]
hyper = { version = "0.14" }
