[package]
name = "peace_domain"
version = "0.1.0"
edition = "2021"
authors = ["Pure-Peace"]
repository = "https://github.com/pure-peace/peace"
homepage = "https://github.com/pure-peace/peace"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
