[package]
name = "peace_logs"
description = "Peace logging framework"
version = "0.1.0"
edition = "2021"
authors = ["Pure-Peace"]
repository = "https://github.com/pure-peace/peace"
homepage = "https://github.com/pure-peace/peace"


[features]
default = []
openapi_axum = ["api_axum", "utoipa/axum_extras", "utoipa-swagger-ui/axum"]
api_axum = ["axum", "serde", "serde_json", "tower-http"]
grpc = ["tonic", "prost", "tonic-build"]
cli = ["clap"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
once_cell = "1.16"

# grpc optional
tonic = { version = "0.8", optional = true }
prost = { version = "0.11", optional = true }

# axum optional
axum = { version = "0.6.0", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
tower-http = { version = "0.3", features = ["auth"], optional = true }

# cli optional
clap = { version = "4.0", features = ["derive"], optional = true }

# openapi optional
utoipa = { version = "2.4.2", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.0.1", features = ["axum"] }

[build-dependencies]
tonic-build = { version = "0.8", optional = true }


[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
