[package]
name = "domain_bancho_state"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[features]


[dependencies]
serde = { workspace = true, features = ["derive"] }

domain_geoip = { workspace = true }

pb_bancho_state = { workspace = true }
pb_geoip = { workspace = true }
