[package]
name = "peace-server"
version = "0.12.2"
authors = ["PurePeace <940857703@qq.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/pure-peace/peace"
description = "PEACE PROTOCOL SERVER"
default-run = "peace-server"

[[bin]]
name = "peace-server"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peace-protocol = { path = "../../framework/protocol", version = "*" }
tokio = { version = "^1.10", features = ["rt-multi-thread", "macros"] }
