[package]
name = "bancho-standalone"
version = "0.1.0"
edition = "2021"
authors = ["Pure-Peace"]
repository = "https://github.com/pure-peace/peace"
homepage = "https://github.com/pure-peace/peace"

[features]
default = ["tls"]
tls = ["peace_api/tls"]

[[bin]]
name = "bancho-standalone-server"
path = "src/main.rs"


[dependencies]
axum = { version = "0.6" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
utoipa = { version = "3.0" }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.1", features = ["derive"] }
clap-serde-derive = { version = "0.2" }


peace_logs = { path = "../../frame/logs", features = ["cli"] }
peace_api = { path = "../../frame/api", features = ["tls"] }

peace_pb = { path = "../../core/pb" }
peace_db = { path = "../../core/db" }
peace_services = { path = "../../core/services" }
peace_repositories = { path = "../../core/repositories" }
