[package]
name = "bancho-standalone"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[features]
default = ["tls"]
tls = ["peace_api/tls"]

[[bin]]
name = "bancho-standalone-server"
path = "src/main.rs"


[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
utoipa = { workspace = true }
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive"] }
clap-serde-derive = { workspace = true }


peace_logs = { workspace = true, features = ["cli"] }
peace_api = { workspace = true, features = ["tls"] }
peace_runtime = { workspace = true }

peace_db = { workspace = true }
peace_repositories = { workspace = true }
peace_snapshot = { workspace = true }

core_bancho = { workspace = true }
core_bancho_state = { workspace = true }
core_gateway = { workspace = true }
core_chat = { workspace = true }
core_geoip = { workspace = true }
core_signature = { workspace = true }

infra_services = { workspace = true }

tools = { workspace = true }
