[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"

[alias]
debug = "run"
start = "run --release"
cross_linux_x86 = "build --release --target x86_64-unknown-linux-musl"
release_build = "build --release"
build_doc = "doc --release --workspace --document-private-items --all-features --no-deps --target-dir ./"
