[package]
name = "core_bancho_state"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []

[dependencies]
tokio = { workspace = true, features = ["parking_lot"] }
tonic = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
num-traits = { workspace = true }
clap = { workspace = true, features = ["derive"] }
clap-serde-derive = { workspace = true }
serde = { workspace = true, features = ["derive"] }

bancho-packets = { workspace = true }
tools = { workspace = true, features = ["all"] }
peace_snapshot = { workspace = true }
peace_unique_id = { workspace = true, features = ["message_id"] }
peace_message_queue = { workspace = true }

peace_rpc_error = { workspace = true }
peace_logs = { workspace = true }
peace_pb = { workspace = true }
peace_domain = { workspace = true }
peace_cfg = { workspace = true }

core_signature = { workspace = true }

infra_users = { workspace = true }
infra_packets = { workspace = true }
infra_services = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
