[package]
name = "domain_bancho"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[features]


[dependencies]
tonic = { workspace = true }
serde = { workspace = true, features = ["derive"] }
bitmask-enum = { workspace = true }
enum-primitive-derive = { workspace = true }
num-traits = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }

peace_pb = { workspace = true }
peace_unique_id = { workspace = true }
