[package]
name = "core_geoip"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
arc-swap = { workspace = true }
memmap2 = { workspace = true }
maxminddb = { workspace = true, features = ["mmap"] }
clap = { workspace = true, features = ["derive"] }
clap-serde-derive = { workspace = true }
serde = { workspace = true, features = ["derive"] }

peace_rpc_error = { workspace = true }
peace_logs = { workspace = true }
peace_pb = { workspace = true }
peace_domain = { workspace = true }
peace_api = { workspace = true }

infra_services = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
