[package]
name = "db-peace-cli"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[[bin]]
name = "db-cli"
path = "src/db-cli.rs"

[[bin]]
name = "db-peace-cli"
path = "src/db-peace-cli.rs"

[[bin]]
name = "db-peace-migrate"
path = "src/db-peace-migrate.rs"


[dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
dotenvy = { workspace = true }
md5 = { workspace = true }
sea-orm-cli = { workspace = true, features = [
    "codegen",
    "cli",
    "runtime-tokio-rustls",
] }
sea-orm-migration = { workspace = true, features = ["runtime-tokio-rustls"] }

clap3 = { workspace = true, features = ["derive"] }
clap4 = { workspace = true, features = ["derive"] }

peace_db = { path = "../../core/db" }
peace_domain = { path = "../../core/domain" }
peace_repositories = { path = "../../core/repositories" }
