[package]
name = "domain_geoip"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[features]


[dependencies]
serde = { workspace = true, features = ["derive"] }

pb_geoip = { workspace = true }
