[package]
name = "peace_domain"
version = "0.1.0"
edition = "2021"
authors = ["Pure-Peace"]
repository = "https://github.com/pure-peace/peace"
homepage = "https://github.com/pure-peace/peace"

[features]


[dependencies]
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
regex = "1.7"
thiserror = "1.0"

# password
rust-argon2 = { version = "1.0" }
rand = { version = "0.8.5" }
once_cell = { version = "1.17" }


tools = { path = "../../lib/tools" }
