[package]
name = "domain_users"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[features]


[dependencies]
serde = { workspace = true, features = ["derive"] }
regex = { workspace = true }
thiserror = { workspace = true }
rust-argon2 = { workspace = true }
rand = { workspace = true }
once_cell = { workspace = true }
