[package]
name = "gateway-server"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[features]
default = ["tls"]
tls = ["peace_api/tls"]

[[bin]]
name = "gateway-server"
path = "src/main.rs"


[dependencies]
axum = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
utoipa = { workspace = true }
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive"] }
clap-serde-derive = { workspace = true }


peace_logs = { path = "../../frame/logs", features = ["grpc", "cli"] }
peace_api = { path = "../../frame/api", features = ["tls"] }

peace_pb = { path = "../../core/pb" }
peace_services = { path = "../../core/services" }
